var LANG = 'es';
var CURRENCY={code:'USD',symbol:'$',name:'US Dollar'};
var CURRENCIES=[
  {code:'USD',symbol:'$',  name:'US Dollar'},
  {code:'EUR',symbol:'€',  name:'Euro'},
  {code:'MXN',symbol:'$',  name:'Mexican Peso'},
  {code:'GBP',symbol:'£',  name:'British Pound'},
  {code:'CAD',symbol:'$',  name:'Canadian Dollar'},
  {code:'ARS',symbol:'$',  name:'Argentine Peso'},
  {code:'COP',symbol:'$',  name:'Colombian Peso'},
  {code:'BRL',symbol:'R$', name:'Brazilian Real'},
  {code:'CLP',symbol:'$',  name:'Chilean Peso'},
  {code:'PEN',symbol:'S/',  name:'Peruvian Sol'},
  {code:'JPY',symbol:'¥',  name:'Japanese Yen'},
  {code:'AUD',symbol:'$',  name:'Australian Dollar'},
  {code:'CHF',symbol:'Fr',  name:'Swiss Franc'},
];
function formatCost(n){
  var num=parseFloat(n)||0;
  return CURRENCY.symbol+num.toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:2});
}
function openCurrencyPicker(){
  var opts=CURRENCIES.map(function(cu){return '<option value="'+cu.code+'" '+(CURRENCY.code===cu.code?'selected':'')+'>'+cu.symbol+' '+cu.code+' - '+cu.name+'</option>';}).join('');
  openMo('<div class="mo-title">💱 Currency</div><p class="s-hint">Select the currency used for all prices in this project.</p><div class="ig"><label>Currency</label><select class="input" id="currency-sel" style="font-size:13px">'+opts+'</select></div><div class="mo-foot"><button class="btn btn-ghost" onclick="closeMo()">Cancel</button><button class="btn btn-primary" onclick="applyCurrency()">Apply</button></div>');
}
function applyCurrency(){
  var sel=document.getElementById('currency-sel');if(!sel)return;
  var found=CURRENCIES.find(function(cu){return cu.code===sel.value;});if(!found)return;
  CURRENCY=found;
  var lbl=document.getElementById('currency-label');if(lbl)lbl.textContent=found.code;
  var p=proj&&proj();if(p){p.currency=found;saveProj(p);}
  closeMo();
  var page=document.querySelector('.pg:not(.hidden)');
  if(page&&page.id==='pg-project'){var active=document.querySelector('.ptab.active');if(active){var tab=active.dataset.tab;var fns={dashboard:renderDash,budget:renderBudget,timeline:renderTimeline,guests:renderGuests,layout:renderLayout,moodboard:renderMoodboard};if(fns[tab])fns[tab]();}}
  toast('Currency: '+found.code+' ('+found.symbol+')','s');
}

var TRANSLATIONS = {
  en: {
    'back_to_events': 'Back to Events',
    'my_events': '📋 My Events',
    'sign_out': '🚪 Sign Out',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'add': 'Add',
    'yes': 'Yes',
    'no': 'No',
    'loading': 'Loading...',
    'confirm_delete': 'Are you sure?',
    'tab_dashboard': 'Dashboard',
    'nav_dashboard': 'Dashboard',
    'nav_events': 'Events',
    'nav_vendors': 'Vendors',
    'nav_tasks': 'Tasks',
    'nav_guests': 'Invitados',
    'nav_layouts': 'Layouts',
    'nav_moodboard': 'Moodboard',
    'nav_analytics': 'Analytics',
    'nav_library': 'My Library',
    'nav_section_events': 'Library',
    'nav_section_more': 'More',
    'tab_budget': 'Budget',
    'tab_timeline': 'Timeline',
    'tab_guests': 'Guests',
    'tab_layout': 'Layout',
    'tab_moodboard': 'Moodboard',
    'tab_viewer3d': '3D Viewer',
    'my_events_title': 'My Events',
    'create_event': 'Create Event',
    'no_events': 'No events yet. Create your first event!',
    'planning': 'Planning',
    'confirmed': 'Confirmed',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'edit_event': 'Edit Event',
    'days_away': 'days away',
    'today': 'Today!',
    'budget_progress': 'Budget Progress',
    'tasks_completed': 'Tasks Completed',
    'event_total_budget': 'Total Event Budget',
    'approved_budget': 'Approved budget',
    'estimated_cost': 'Estimated Cost (All Vendors)',
    'of_approved': 'of approved',
    'actual_paid': 'Actual Paid',
    'budget_variance': 'Budget Variance',
    'under_budget': '✓ Under Budget',
    'over_budget': '⚠ Over Budget',
    'sort_by': 'Sort',
    'sort_name': 'Name',
    'sort_date': 'Date',
    'sort_type': 'Type',
    'sort_location': 'Location',
    'sort_budget': 'Budget',
    'sort_created': 'Created Date',
    'view_grid': 'Grid',
    'view_list': 'List',
    'analytics_title': 'Analytics',
    'analytics_sub': 'Insights across all your events',
    'period_1m': '1 Month',
    'period_3m': '3 Months',
    'period_6m': '6 Months',
    'period_1y': '1 Year',
    'period_thisyear': 'This Year',
    'period_next1y': 'Next 12 mo',
    'period_alltime': 'All Time',
    'period_custom': 'Custom',
    'filter_all_dates': 'All Dates',
    'filter_date_range': 'Date Range',
    'lib_title': 'My Library',
    'lib_sub': 'Save and reuse vendors, tasks, layouts and more across projects',
    'lib_vendors': 'Vendors',
    'lib_tasks': 'Tasks',
    'lib_layouts': 'Layouts',
    'lib_tables': 'Tables',
    'lib_elements': 'Elements',
    'lib_chairs': 'Chairs',
    'lib_centerpieces': 'Centerpieces',
    'lib_moodboards': 'Moodboards',
    'lib_save_to': 'Save to Library',
    'lib_load_from': 'Load from Library',
    'lib_empty': 'Nothing saved here yet',
    'lib_empty_sub': 'Save items from any project to reuse them here',
    'lib_saved': 'Saved to library',
    'lib_loaded': 'Loaded into project',
    'lib_delete_confirm': 'Remove from library?',
    'lib_save_name': 'Name for this library entry',
    'lib_save_btn': 'Save to Library',
    'lib_load_btn': 'Load into Project',
    'lib_add_vendor': 'Save Vendors',
    'lib_add_task': 'Save Tasks',
    'lib_add_layout': 'Save Layout',
    'lib_add_moodboard': 'Save Moodboard',
    'lib_add_types': 'Save Types',
    'lib_select_to_save': 'Select items to save:',
    'lib_select_all': 'Select All',
    'analytics_events': 'Events in Period',
    'analytics_avg_budget': 'Avg Budget',
    'analytics_avg_guests': 'Avg Guests',
    'analytics_top_vendors': 'Top Vendor Categories',
    'analytics_by_type': 'Events by Type',
    'analytics_by_status': 'Events by Status',
    'analytics_timeline': 'Event Timeline',
    'analytics_no_data': 'No events in this period',
    'export_pdf_title': 'Export Presentation PDF',
    'export_pdf_select': 'Select sections to include:',
    'export_pdf_generate': 'Generate PDF',
    'export_pdf_cancel': 'Cancel',
    'section_dashboard': 'Overview & Details',
    'section_budget': 'Budget Summary',
    'section_timeline': 'Task Timeline',
    'section_guests': 'Guest List',
    'section_moodboard': 'Moodboard',
    'guests_confirmed': 'Guests Confirmed',
    'vendors_hired': 'Vendors Hired',
    'budget_label': 'Budget',
    'paid': 'Paid',
    'balance': 'Balance',
    'add_vendor': 'Add Vendor',
    'add_task': 'Add Task',
    'quick_actions': 'Quick Actions',
    'upcoming_tasks': 'Upcoming Tasks',
    'no_tasks': 'No upcoming tasks',
    'budget_management': 'Budget Management',
    'hired_vendors': 'Hired Vendors',
    'comparisons': 'Comparisons',
    'no_hired_vendors': 'No hired vendors yet.',
    'no_comparison_vendors': 'No comparison vendors yet.',
    'view_details': 'View Details',
    'hire': 'Hire',
    'unhire': 'Unhire',
    'hired': 'Hired',
    'services': 'Services',
    'budget_estimate': 'Budget Estimate',
    'contact': 'Contact',
    'phone': 'Phone',
    'notes': 'Notes',
    'add_payment': 'Add Payment',
    'comparison': 'Comparison',
    'timeline': 'Timeline & Calendar',
    'gantt_view': 'Gantt Chart',
    'calendar_view': 'Calendar',
    'list_view': 'Task List',
    'add_task_btn': 'Add Task',
    'no_tasks_yet': 'No tasks yet',
    'no_tasks_found': 'No tasks match your search',
    'search_tasks': 'Search tasks...',
    'task': 'Task',
    'due_date': 'Due Date',
    'assignee': 'Assignee',
    'done': 'Done',
    'overdue': 'Overdue',
    'pending': 'Pending',
    'guest_management': 'Guest Management',
    'add_guest': 'Add Guest',
    'import_excel': 'Import Excel',
    'export_list': 'Export List',
    'name': 'Name',
    'email': 'Email',
    'category': 'Category',
    'rsvp': 'RSVP',
    'table_num': 'Table #',
    'meal': 'Meal',
    'dietary': 'Dietary',
    'plus_one': '+1',
    'all_guests': 'All Guests',
    'confirmed_guests': 'Confirmed',
    'declined': 'Declined',
    'pending_guests': 'Pending',
    'total_guests': 'Total Guests',
    'layout_designer': 'Layout Designer',
    'tables': 'Tables',
    'event_elements': 'Event Elements',
    'controls': 'Controls',
    'snap_grid': 'Snap Grid',
    'grid_size': 'Grid Size (px)',
    'select_all': 'Select All',
    'clear_all': 'Clear All',
    'quick_create': 'Quick Create',
    'table_type': 'Table Type',
    'num_tables': '# Tables',
    'num_chairs': '# Chairs',
    'columns': 'Columns',
    'spacing': 'Spacing (m)',
    'create_tables': '⚡ Create Tables',
    'properties': 'Properties',
    'label': 'Label',
    'width': 'Width',
    'height': 'Height',
    'seats': 'Seats',
    'fill': 'Fill',
    'label_color': 'Label Color',
    'chair_style': 'Chair Style',
    'centerpiece': 'Centerpiece',
    'cost': 'Cost ($)',
    'items': 'Items',
    'legend': 'Legend',
    'chair_styles': 'Chair Styles',
    'centerpieces': 'Centerpieces',
    'chairs_section': 'Chairs',
    'centrepieces_section': 'Centros de Mesa',
    'floorplan_section': '🗺️ Floorplan',
    'create_general_layout': 'Create General Layout',
    'layout_quote_title': 'Layout Quote',
    'layout_quote_sub': 'Auto-priced from the layout plus custom extras',
    'layout_quote_empty': 'No priced items yet',
    'layout_quote_empty_sub': 'Add layout items or custom extras to build the quote.',
    'layout_quote_open': 'Open Quote',
    'layout_quote_hide': 'Hide Quote',
    'layout_quote_show': 'Show Quote',
    'layout_quote_add_custom': 'Add Custom Item',
    'layout_quote_auto': 'Layout Items',
    'layout_quote_custom': 'Custom Items',
    'layout_quote_base': 'Base Price',
    'layout_quote_chair_cost': 'Chair Cost',
    'layout_quote_centerpiece_cost': 'Centerpiece Cost',
    'layout_quote_unit_total': 'Unit Total',
    'layout_quote_seats_unit': 'Seats/Unit',
    'layout_quote_row_total': 'Subtotal',
    'layout_quote_unit_price': 'Unit Price',
    'layout_quote_quantity': 'Qty',
    'layout_quote_item': 'Item',
    'layout_quote_actions': 'Actions',
    'layout_quote_custom_name': 'Custom item',
    'layout_quote_custom_category': 'Category',
    'layout_quote_notes': 'Notes',
    'properties': 'Properties',
    'measure_distances': 'Measure distances',
    'save_layout': '💾 Save Layout',
    'layouts': '📐 Layouts',
    'export': '📄 Export',
    'round_table': 'Round Table',
    'rect_table': 'Rectangular Table',
    'oval_table': 'Oval Table',
    'head_table': 'Head / Sweetheart Table',
    'dance_floor': 'Dance Floor',
    'bar_buffet': 'Bar / Buffet',
    'stage': 'Stage / Podium',
    'gift_table': 'Gift Table',
    'photo_booth': 'Photo Booth',
    'align': 'Align',
    'delete_selected': 'Delete',
    'moodboard_library': 'Moodboard Library',
    'images': 'images',
    'folders': 'folders',
    'add_images': 'Add Images',
    'new_folder': 'New Folder',
    'uncategorized': 'Uncategorized',
    'move_to_folder': 'Move to folder',
    'delete_image': 'Delete Image',
    'delete_folder': 'Delete Folder',
    'edit_event_title': 'Edit Event',
    'create_event_title': 'Create Event',
    'event_name': 'Event Name',
    'client_name': 'Client',
    'event_date': 'Date',
    'event_type': 'Type',
    'location': 'Location',
    'description': 'Description',
    'total_budget': 'Total Budget',
    'status': 'Status',
    'manage_events': 'Manage all your event projects',
    'social_private': 'Social / Private',
    'corporate': 'Corporate',
    'community': 'Community',
    'government': 'Government',
    'education': 'Education',
    'recent_vendors': 'Recent Vendors',
    'no_vendors': 'No vendors yet',
    'create_event_hint': 'Create your first event to get started',
    'edit_vendor': 'Edit Vendor',
    'edit_guest': 'Edit Guest',
    'edit_task': 'Edit Task',
    'of': 'of',
    'total': 'total',
    'items': 'items',
    'floorplan': 'Floorplan',
    'calibrate_scale': 'Scale',
    'upload_floorplan': 'Upload Floorplan',
    'status_planning': 'To be Confirmed',
    'status_confirmed': 'Confirmed',
    'status_in_progress': 'In Progress',
    'status_completed': 'Completed',
    'status_cancelled': 'Cancelled',
    'type_social': 'Social / Private',
    'type_corporate': 'Corporate',
    'type_community': 'Community',
    'type_government': 'Government',
    'type_education': 'Education',
    'client': 'Client',
    'budget_used': 'Budget Used',
    'stat_vendors': 'Vendors',
    'stat_guests': 'Guests',
    'stat_event_date': 'Event Date',
    'hired_of': 'hired of',
    'total_guests_sub': 'total guests',
    'days_ago': 'days ago',
    'budget_management_title': 'Budget Management',
    'paid_label': 'Paid',
    'balance_label': 'Balance',
    'mark_as_hired': 'Mark as Hired',
    'add_payment_btn': 'Add Payment',
    'details_btn': 'Details',
    'payment_progress': 'Payment Progress',
    'payment_history': 'Payment History',
    'receipt_btn': 'Receipt',
    'vendor_name_lbl': 'Vendor Name',
    'sub_category': 'Sub-category',
    'services_lbl': 'Services',
    'contact_email': 'Contact Email',
    'budget_field': 'Budget ($)',
    'vendor_status': 'Status',
    'save_vendor': 'Save Vendor',
    'save_event': 'Save Event',
    'amount_field': 'Amount ($)',
    'date_field': 'Date',
    'note_field': 'Note',
    'upload_receipt': 'Click to upload image',
    'add_payment_save': 'Add Payment',
    'timeline_sub': 'Gantt · Task List · Calendar',
    'total_tasks': 'Total Tasks',
    'completed_tasks': 'Completed',
    'overdue_tasks': 'Overdue',
    'progress': 'Progress',
    'tasks_lbl': 'tasks',
    'overdue_lbl': 'Overdue',
    'tasks_overdue_sub': 'tasks overdue',
    'tasks_sub': 'tasks',
    'unassigned': 'Unassigned',
    'task_title_lbl': 'Task Title',
    'description_lbl': 'Description',
    'due_date_lbl': 'Due Date',
    'color_label_lbl': 'Color Label',
    'save_task': 'Save Task',
    'download_template': 'Download Template',
    'import_csv': 'Import CSV',
    'search_guests': 'Search guests...',
    'sort_rsvp': 'Sort: RSVP',
    'sort_table': 'Sort: Table',
    'sort_category': 'Sort: Category',
    'asc': '↑ Asc',
    'desc': '↓ Desc',
    'col_name': 'Name',
    'col_contact': 'Contact',
    'col_category': 'Category',
    'col_rsvp': 'RSVP',
    'col_table': 'Table',
    'col_plus_one': '+1',
    'col_meal': 'Meal',
    'col_notes': 'Notes',
    'col_actions': 'Actions',
    'no_guests_found': 'No guests found',
    'full_name': 'Full Name',
    'rsvp_status': 'RSVP Status',
    'rsvp_confirmed': 'Confirmed',
    'rsvp_declined': 'Declined',
    'table_number': 'Table Number',
    'plus_one_q': 'Plus One?',
    'meal_pref': 'Meal Preference',
    'dietary_rest': 'Dietary Restrictions',
    'save_guest': 'Save Guest',
    'tables_count': 'Tables',
    'seated_count': 'Seated',
    'table_header': 'Table',
    'guests_lbl': 'guests',
    'floorplan_lbl': '🗺️ Plano',
    'upload_floorplan_lbl': 'Upload Floorplan',
    'items_count': 'Items',
    'tables_lbl': 'tables',
    'chairs_lbl': 'chairs',
    'rotate_lbl': 'Rotate',
    'edit_table_types': 'Edit Table Types',
    'edit_event_elements': 'Edit Event Elements',
    'edit_chairs': 'Chairs',
    'edit_centerpieces': 'Centros de Mesa',
    'col_name': 'Name',
    'col_shape': 'Shape',
    'col_chairs': 'Chairs',
    'col_price': 'Price',
    'col_color': 'Color',
    'col_photo': 'Photo',
    'shape_round': '⭕ Round',
    'shape_rect': '▬ Rect',
    'shape_square': '⬛ Square',
    'add_custom_table': '+ Add Custom Table',
    'add_custom_element': '+ Add Custom Element',
    'add_new_chair': '+ Add New Chair Style',
    'add_new_centerpiece': '+ Add New Centerpiece',
    'vcat_venue': 'Venue & Rentals',
    'vcat_food': 'Food & Beverage',
    'vcat_floral': 'Floral & Decor',
    'vcat_photo': 'Photography & Video',
    'vcat_entertainment': 'Entertainment & Music',
    'vcat_staffing': 'Staffing',
    'vcat_transport': 'Transportation',
    'vcat_admin': 'Admin & Compliance',
    'vcat_other': 'Other',
    'round_table_lbl': 'Round Table',
    'rect_table_lbl': 'Rect Table',
    'square_table_lbl': 'Square Table',
    'scroll_zoom': 'Scroll to zoom',
    'space_pan': 'Space+drag to pan',
    'drag_select': 'Drag on empty area to multi-select',
    'copy_paste': 'Ctrl+C / Ctrl+V to copy/paste',
    'del_remove': 'Del / Backspace to remove',
    'shift_drag_add': 'Shift+drag to add to selection',
    'ctrl_drag_remove': 'Ctrl+drag to deselect',
    'ctrl_click_desel': 'Ctrl+click to deselect item',
    'shift_click_add': 'Shift+click to add item',
    'opacity_lbl': 'Opacity',
    'moodboard_library_title': 'Moodboard Library',
    'new_folder_btn': 'New Folder',
    'add_to_root_btn': 'Add to Root',
    'main_menu_btn': 'Hide Menu',
    'export_pdf_btn': 'Export Project PDF',
    'create_folder_btn': 'Create Folder',
    'upload_images_btn': 'Upload Images',
    'no_images_yet': 'No images yet',
    'start_moodboard': 'Start your moodboard',
    'start_moodboard_sub': 'Create folders to organize your vision, or upload images directly',
    'add_label': 'Add label...',
    'saved': 'Saved',
    'deleted': 'Deleted',
    'error': 'Error',
    'updated': 'Updated',
  },
  es: {
    'back_to_events': 'Volver a Eventos',
    'my_events': '📋 Mis Eventos',
    'sign_out': '🚪 Cerrar Sesión',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'close': 'Cerrar',
    'add': 'Agregar',
    'yes': 'Sí',
    'no': 'No',
    'loading': 'Cargando...',
    'confirm_delete': '¿Estás seguro?',
    'tab_dashboard': 'Panel',
    'nav_dashboard': 'Panel',
    'nav_events': 'Eventos',
    'nav_vendors': 'Proveedores',
    'nav_tasks': 'Tareas',
    'nav_guests': 'Invitados',
    'nav_layouts': 'Layouts',
    'nav_moodboard': 'Moodboard',
    'nav_analytics': 'Estadísticas',
    'nav_library': 'Mi Biblioteca',
    'nav_section_events': 'Biblioteca',
    'nav_section_more': 'Más',
    'tab_budget': 'Presupuesto',
    'tab_timeline': 'Cronograma',
    'tab_guests': 'Invitados',
    'tab_layout': 'Diseño',
    'tab_moodboard': 'Moodboard',
    'tab_viewer3d': 'Vista 3D',
    'my_events_title': 'Mis Eventos',
    'create_event': 'Crear Evento',
    'no_events': '¡Aún no hay eventos. Crea tu primer evento!',
    'planning': 'Planificación',
    'confirmed': 'Confirmado',
    'completed': 'Completado',
    'cancelled': 'Cancelado',
    'edit_event': 'Editar Evento',
    'days_away': 'días restantes',
    'today': '¡Hoy!',
    'budget_progress': 'Avance del Presupuesto',
    'tasks_completed': 'Tareas Completadas',
    'event_total_budget': 'Presupuesto Total del Evento',
    'approved_budget': 'Presupuesto aprobado',
    'estimated_cost': 'Costo Estimado (Todos los Proveedores)',
    'of_approved': 'del aprobado',
    'actual_paid': 'Pagado Real',
    'budget_variance': 'Variación de Presupuesto',
    'under_budget': '✓ Bajo Presupuesto',
    'over_budget': '⚠ Sobre Presupuesto',
    'sort_by': 'Ordenar',
    'sort_name': 'Nombre',
    'sort_date': 'Fecha',
    'sort_type': 'Tipo',
    'sort_location': 'Ubicación',
    'sort_budget': 'Presupuesto',
    'sort_created': 'Fecha de Creación',
    'view_grid': 'Cuadrícula',
    'view_list': 'Lista',
    'analytics_title': 'Analítica',
    'analytics_sub': 'Resumen de todos tus eventos',
    'period_1m': '1 Mes',
    'period_3m': '3 Meses',
    'period_6m': '6 Meses',
    'period_1y': '1 Año',
    'period_thisyear': 'Este Año',
    'period_next1y': 'Próximos 12 m',
    'period_alltime': 'Todo',
    'period_custom': 'Personalizado',
    'filter_all_dates': 'Todas las Fechas',
    'filter_date_range': 'Rango de Fechas',
    'lib_title': 'Mi Biblioteca',
    'lib_sub': 'Guarda y reutiliza proveedores, tareas, planos y más en diferentes proyectos',
    'lib_vendors': 'Proveedores',
    'lib_tasks': 'Tareas',
    'lib_layouts': 'Layouts',
    'lib_tables': 'Mesas',
    'lib_elements': 'Elementos',
    'lib_chairs': 'Sillas',
    'lib_centerpieces': 'Centros de Mesa',
    'lib_moodboards': 'Moodboards',
    'lib_save_to': 'Guardar en Biblioteca',
    'lib_load_from': 'Cargar desde Biblioteca',
    'lib_empty': 'Nada guardado aquí aún',
    'lib_empty_sub': 'Guarda elementos de cualquier proyecto para reutilizarlos aquí',
    'lib_saved': 'Guardado en biblioteca',
    'lib_loaded': 'Cargado en el proyecto',
    'lib_delete_confirm': '¿Eliminar de la biblioteca?',
    'lib_save_name': 'Nombre para esta entrada de biblioteca',
    'lib_save_btn': 'Guardar en Biblioteca',
    'lib_load_btn': 'Cargar en Proyecto',
    'lib_add_vendor': 'Guardar Proveedores',
    'lib_add_task': 'Guardar Tareas',
    'lib_add_layout': 'Guardar Plano',
    'lib_add_moodboard': 'Guardar Moodboard',
    'lib_add_types': 'Guardar Tipos',
    'lib_select_to_save': 'Selecciona elementos a guardar:',
    'lib_select_all': 'Seleccionar Todo',
    'analytics_events': 'Eventos en el Período',
    'analytics_avg_budget': 'Presupuesto Promedio',
    'analytics_avg_guests': 'Invitados Promedio',
    'analytics_top_vendors': 'Categorías de Proveedores Más Usadas',
    'analytics_by_type': 'Eventos por Tipo',
    'analytics_by_status': 'Eventos por Estado',
    'analytics_timeline': 'Línea de Tiempo de Eventos',
    'analytics_no_data': 'Sin eventos en este período',
    'export_pdf_title': 'Exportar Presentación PDF',
    'export_pdf_select': 'Seleccionar secciones a incluir:',
    'export_pdf_generate': 'Generar PDF',
    'export_pdf_cancel': 'Cancelar',
    'section_dashboard': 'Resumen y Detalles',
    'section_budget': 'Resumen de Presupuesto',
    'section_timeline': 'Cronograma de Tareas',
    'section_guests': 'Lista de Invitados',
    'section_moodboard': 'Tablero de Inspiración',
    'guests_confirmed': 'Invitados Confirmados',
    'vendors_hired': 'Proveedores Contratados',
    'budget_label': 'Presupuesto',
    'paid': 'Pagado',
    'balance': 'Saldo',
    'add_vendor': 'Agregar Proveedor',
    'add_task': 'Agregar Tarea',
    'quick_actions': 'Acciones Rápidas',
    'upcoming_tasks': 'Próximas Tareas',
    'no_tasks': 'Sin tareas próximas',
    'budget_management': 'Gestión de Presupuesto',
    'hired_vendors': 'Proveedores Contratados',
    'comparisons': 'Comparaciones',
    'no_hired_vendors': 'Aún no hay proveedores contratados.',
    'no_comparison_vendors': 'Aún no hay proveedores en comparación.',
    'view_details': 'Ver Detalles',
    'hire': 'Contratar',
    'unhire': 'Descontratar',
    'hired': 'Contratado',
    'services': 'Servicios',
    'budget_estimate': 'Estimado de Presupuesto',
    'contact': 'Contacto',
    'phone': 'Teléfono',
    'notes': 'Notas',
    'add_payment': 'Agregar Pago',
    'comparison': 'Comparación',
    'timeline': 'Cronograma y Calendario',
    'gantt_view': 'Diagrama Gantt',
    'calendar_view': 'Calendario',
    'list_view': 'Lista de Tareas',
    'add_task_btn': 'Agregar Tarea',
    'no_tasks_yet': 'Sin tareas aún',
    'task': 'Tarea',
    'due_date': 'Fecha Límite',
    'assignee': 'Responsable',
    'done': 'Hecho',
    'overdue': 'Vencido',
    'pending': 'Pendiente',
    'guest_management': 'Gestión de Invitados',
    'add_guest': 'Agregar Invitado',
    'import_excel': 'Importar Excel',
    'export_list': 'Exportar Lista',
    'name': 'Nombre',
    'email': 'Correo',
    'category': 'Categoría',
    'rsvp': 'RSVP',
    'table_num': 'Mesa #',
    'meal': 'Menú',
    'dietary': 'Dieta',
    'plus_one': '+1',
    'all_guests': 'Todos',
    'confirmed_guests': 'Confirmados',
    'declined': 'Rechazados',
    'pending_guests': 'Pendientes',
    'total_guests': 'Total Invitados',
    'layout_designer': 'Diseñador de Espacio',
    'tables': 'Mesas',
    'event_elements': 'Elementos del Evento',
    'controls': 'Controles',
    'snap_grid': 'Cuadrícula',
    'grid_size': 'Tamaño de Cuadrícula (px)',
    'select_all': 'Seleccionar Todo',
    'clear_all': 'Limpiar Todo',
    'quick_create': 'Creación Rápida',
    'table_type': 'Tipo de Mesa',
    'num_tables': '# Mesas',
    'num_chairs': '# Sillas',
    'columns': 'Columnas',
    'spacing': 'Espaciado (m)',
    'create_tables': '⚡ Crear Mesas',
    'properties': 'Propiedades',
    'label': 'Etiqueta',
    'width': 'Ancho',
    'height': 'Alto',
    'seats': 'Asientos',
    'fill': 'Color de Relleno',
    'label_color': 'Color de Texto',
    'chair_style': 'Estilo de Silla',
    'centerpiece': 'Centro de Mesa',
    'cost': 'Costo ($)',
    'items': 'Elementos',
    'legend': 'Leyenda',
    'chair_styles': 'Estilos de Silla',
    'centerpieces': 'Centros de Mesa',
    'chairs_section': 'Sillas',
    'centrepieces_section': 'Centros de Mesa',
    'floorplan_section': '🗺️ Plano',
    'create_general_layout': 'Crear Layout General',
    'layout_quote_title': 'Cotizacion del Layout',
    'layout_quote_sub': 'Precio automatico desde el layout mas extras manuales',
    'layout_quote_empty': 'Aun no hay elementos con precio',
    'layout_quote_empty_sub': 'Agrega elementos al layout o extras manuales para armar la cotizacion.',
    'layout_quote_open': 'Abrir Cotizacion',
    'layout_quote_hide': 'Ocultar Cotizacion',
    'layout_quote_show': 'Mostrar Cotizacion',
    'layout_quote_add_custom': 'Agregar Item Manual',
    'layout_quote_auto': 'Items del Layout',
    'layout_quote_custom': 'Items Manuales',
    'layout_quote_base': 'Precio Base',
    'layout_quote_chair_cost': 'Costo Sillas',
    'layout_quote_centerpiece_cost': 'Costo Centro',
    'layout_quote_unit_total': 'Total Unitario',
    'layout_quote_seats_unit': 'Asientos/Unidad',
    'layout_quote_row_total': 'Subtotal',
    'layout_quote_unit_price': 'Precio Unitario',
    'layout_quote_quantity': 'Cant.',
    'layout_quote_item': 'Item',
    'layout_quote_actions': 'Acciones',
    'layout_quote_custom_name': 'Item manual',
    'layout_quote_custom_category': 'Categoria',
    'layout_quote_notes': 'Notas',
    'properties': 'Propiedades',
    'measure_distances': 'Medir distancias',
    'save_layout': '💾 Guardar Diseño',
    'layouts': '📐 Layouts',
    'export': '📄 Exportar',
    'round_table': 'Mesa Redonda',
    'rect_table': 'Mesa Rectangular',
    'oval_table': 'Mesa Ovalada',
    'head_table': 'Mesa Principal / de Honor',
    'dance_floor': 'Pista de Baile',
    'bar_buffet': 'Bar / Buffet',
    'stage': 'Escenario / Pódium',
    'gift_table': 'Mesa de Regalos',
    'photo_booth': 'Cabina de Fotos',
    'align': 'Alinear',
    'delete_selected': 'Eliminar',
    'moodboard_library': 'Biblioteca de Inspiración',
    'images': 'imágenes',
    'folders': 'carpetas',
    'add_images': 'Agregar Imágenes',
    'new_folder': 'Nueva Carpeta',
    'uncategorized': 'Sin Categoría',
    'move_to_folder': 'Mover a carpeta',
    'delete_image': 'Eliminar Imagen',
    'delete_folder': 'Eliminar Carpeta',
    'edit_event_title': 'Editar Evento',
    'create_event_title': 'Crear Evento',
    'event_name': 'Nombre del Evento',
    'client_name': 'Cliente',
    'event_date': 'Fecha',
    'event_type': 'Tipo',
    'location': 'Lugar',
    'description': 'Descripción',
    'total_budget': 'Presupuesto Total',
    'status': 'Estado',
    'manage_events': 'Administra todos tus proyectos de eventos',
    'social_private': 'Social / Privado',
    'corporate': 'Corporativo',
    'community': 'Comunitario',
    'government': 'Gubernamental',
    'education': 'Educativo',
    'recent_vendors': 'Proveedores Recientes',
    'no_vendors': 'Aún no hay proveedores',
    'create_event_hint': 'Crea tu primer evento para comenzar',
    'edit_vendor': 'Editar Proveedor',
    'edit_guest': 'Editar Invitado',
    'edit_task': 'Editar Tarea',
    'of': 'de',
    'total': 'total',
    'items': 'elementos',
    'floorplan': 'Plano',
    'calibrate_scale': 'Escala',
    'upload_floorplan': 'Subir Plano',
    'status_planning': 'Por Confirmar',
    'status_confirmed': 'Confirmado',
    'status_in_progress': 'En Progreso',
    'status_completed': 'Completado',
    'status_cancelled': 'Cancelado',
    'type_social': 'Social / Privado',
    'type_corporate': 'Corporativo',
    'type_community': 'Comunitario',
    'type_government': 'Gubernamental',
    'type_education': 'Educativo',
    'client': 'Cliente',
    'budget_used': 'Presupuesto Usado',
    'stat_vendors': 'Proveedores',
    'stat_guests': 'Invitados',
    'stat_event_date': 'Fecha del Evento',
    'hired_of': 'contratados de',
    'total_guests_sub': 'invitados en total',
    'days_ago': 'días atrás',
    'budget_management_title': 'Gestión de Presupuesto',
    'paid_label': 'Pagado',
    'balance_label': 'Saldo',
    'mark_as_hired': 'Marcar como Contratado',
    'add_payment_btn': 'Agregar Pago',
    'details_btn': 'Detalles',
    'payment_progress': 'Progreso de Pago',
    'payment_history': 'Historial de Pagos',
    'receipt_btn': 'Recibo',
    'vendor_name_lbl': 'Nombre del Proveedor',
    'sub_category': 'Sub-categoría',
    'services_lbl': 'Servicios',
    'contact_email': 'Correo de Contacto',
    'budget_field': 'Presupuesto ($)',
    'vendor_status': 'Estado',
    'save_vendor': 'Guardar Proveedor',
    'save_event': 'Guardar Evento',
    'amount_field': 'Monto ($)',
    'date_field': 'Fecha',
    'note_field': 'Nota',
    'upload_receipt': 'Click para subir imagen',
    'add_payment_save': 'Agregar Pago',
    'timeline_sub': 'Gantt · Lista de Tareas · Calendario',
    'total_tasks': 'Total Tareas',
    'completed_tasks': 'Completadas',
    'overdue_tasks': 'Vencidas',
    'progress': 'Progreso',
    'tasks_lbl': 'tareas',
    'overdue_lbl': 'Vencida',
    'tasks_overdue_sub': 'Tareas Vencidas',
    'tasks_sub': 'Tareas',
    'unassigned': 'Sin asignar',
    'task_title_lbl': 'Título de Tarea',
    'description_lbl': 'Descripción',
    'due_date_lbl': 'Fecha Límite',
    'color_label_lbl': 'Etiqueta de Color',
    'save_task': 'Guardar Tarea',
    'download_template': 'Descargar Plantilla',
    'import_csv': 'Importar CSV',
    'search_tasks': 'Buscar tareas...',
    'no_tasks_found': 'No se encontraron tareas',
    'search_guests': 'Buscar invitados...',
    'sort_rsvp': 'Ordenar: RSVP',
    'sort_table': 'Ordenar: Mesa',
    'sort_category': 'Ordenar: Categoría',
    'asc': '↑ Asc',
    'desc': '↓ Desc',
    'col_name': 'Nombre',
    'col_contact': 'Contacto',
    'col_category': 'Categoría',
    'col_rsvp': 'RSVP',
    'col_table': 'Mesa',
    'col_plus_one': '+1',
    'col_meal': 'Menú',
    'col_notes': 'Notas',
    'col_actions': 'Acciones',
    'no_guests_found': 'No se encontraron invitados',
    'full_name': 'Nombre Completo',
    'rsvp_status': 'Estado RSVP',
    'rsvp_confirmed': 'Confirmado',
    'rsvp_declined': 'Rechazado',
    'table_number': 'Número de Mesa',
    'plus_one_q': '¿Acompañante?',
    'meal_pref': 'Preferencia de Menú',
    'dietary_rest': 'Restricciones Alimentarias',
    'save_guest': 'Guardar Invitado',
    'tables_count': 'Mesas',
    'seated_count': 'Sentados',
    'table_header': 'Mesa',
    'guests_lbl': 'invitados',
    'floorplan_lbl': '🗺️ Plano',
    'upload_floorplan_lbl': 'Subir Plano',
    'items_count': 'Elementos',
    'tables_lbl': 'mesas',
    'chairs_lbl': 'sillas',
    'rotate_lbl': 'Rotar',
    'edit_table_types': 'Editar Tipos de Mesa',
    'edit_event_elements': 'Editar Elementos del Evento',
    'edit_chairs': 'Sillas',
    'edit_centerpieces': 'Centros de Mesa',
    'col_name': 'Nombre',
    'col_shape': 'Forma',
    'col_chairs': 'Sillas',
    'col_price': 'Precio',
    'col_color': 'Color',
    'col_photo': 'Foto',
    'shape_round': '⭕ Redonda',
    'shape_rect': '▬ Rectangular',
    'shape_square': '⬛ Cuadrada',
    'add_custom_table': '+ Agregar Mesa Personalizada',
    'add_custom_element': '+ Agregar Elemento Personalizado',
    'add_new_chair': '+ Agregar Estilo de Silla',
    'add_new_centerpiece': '+ Agregar Centro de Mesa',
    'vcat_venue': 'Venue y Rentas',
    'vcat_food': 'Alimentos y Bebidas',
    'vcat_floral': 'Floral y Decoración',
    'vcat_photo': 'Fotografía y Video',
    'vcat_entertainment': 'Entretenimiento y Música',
    'vcat_staffing': 'Personal',
    'vcat_transport': 'Transporte',
    'vcat_admin': 'Administración y Permisos',
    'vcat_other': 'Otros',
    'round_table_lbl': 'Mesa Redonda',
    'rect_table_lbl': 'Mesa Rectangular',
    'square_table_lbl': 'Mesa Cuadrada',
    'scroll_zoom': 'Scroll para zoom',
    'space_pan': 'Espacio+arrastrar para mover',
    'drag_select': 'Arrastrar en área vacía para selección múltiple',
    'copy_paste': 'Ctrl+C / Ctrl+V para copiar/pegar',
    'del_remove': 'Supr / Retroceso para eliminar',
    'shift_drag_add': 'Shift+arrastrar para agregar a selección',
    'ctrl_drag_remove': 'Ctrl+arrastrar para deseleccionar',
    'ctrl_click_desel': 'Ctrl+clic para deseleccionar',
    'shift_click_add': 'Shift+clic para agregar a selección',
    'opacity_lbl': 'Opacidad',
    'moodboard_library_title': 'Biblioteca de Inspiración',
    'new_folder_btn': 'Nueva Carpeta',
    'add_to_root_btn': 'Agregar aquí',
    'main_menu_btn': 'Ocultar Menú',
    'export_pdf_btn': 'Exportar PDF del Proyecto',
    'create_folder_btn': 'Crear Carpeta',
    'upload_images_btn': 'Subir Imágenes',
    'no_images_yet': 'Sin imágenes aún',
    'start_moodboard': 'Comienza tu moodboard',
    'start_moodboard_sub': 'Crea carpetas para organizar tu visión, o sube imágenes directamente',
    'add_label': 'Agregar etiqueta...',
    'saved': 'Guardado',
    'deleted': 'Eliminado',
    'error': 'Error',
    'updated': 'Actualizado',
  }
};
